language: node_js
addons:
  chrome: stable
node_js:
  - "4"
before_script:
  - npm install
script: npm run test:single
dist: trusty
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless