language: node_js
dist: trusty
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless
node_js:
  - "0.10"
before_script:
  - npm install uglify-js -g
  - npm install
  - npm run build
script: npm run test-single-run